server:
  port: 8083

spring:
  application:
    name: transfer-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Service URLs
services:
  checking-account: http://localhost:8082
  saving-account: http://localhost:8081
