server:
  port: 8901

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ProductService

# Ribbon configuration for load balancing
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 5000
  ConnectTimeout: 5000

# Sleuth and Zipkin configuration for distributed tracing
sleuth:
  sampler:
    probability: 1.0  # Sample 100% of requests for tracing
  web:
    client:
      enabled: true
  messaging:
    enabled: true
  r2dbc:
    enabled: true

# Zipkin configuration
zipkin:
  base-url: http://localhost:9411
  sender:
    type: web
  enabled: true
