server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: StockService

# Custom property to identify this instance
stock:
  instance: 1
  value: 100
